#!/usr/bin/with-contenv sh

mkdir -p \
    /srv/caddy \
    /srv/caddy/log \
    /srv/xray \
    /srv/xray/log

touch /srv/xray/log/access.log
touch /srv/xray/log/error.log

CERTPATH="/srv/caddy/certificates/acme-v02.api.letsencrypt.org-directory"
UUID=${UUID:-"e53b463e-1195-5223-8637-c259c4a2010f"}

if [ ! -f /srv/caddy/Caddyfile ]; then
    cp /defaults/Caddyfile /srv/caddy/Caddyfile
    if [[ -z "${DOMAIN}" || -z "${CFKEY}" ]]; then
        sed -i -e "/^https:\/\/{env.DOMAIN}:8443/,$ d" /srv/caddy/Caddyfile
        false | cp -i /defaults/example.key /srv/xray/private.key 2>/dev/null
        false | cp -i /defaults/example.crt /srv/xray/fullchain.crt 2>/dev/null
    else
        ln -sf $CERTPATH/${DOMAIN}/${DOMAIN}.crt /srv/xray/fullchain.crt
        ln -sf $CERTPATH/${DOMAIN}/${DOMAIN}.key /srv/xray/private.key
    fi
fi

if [ ! -f /srv/xray/config.json ]; then
    cp /defaults/xray.json /srv/xray/config.json
    sed -i -e "s/__UUID__/$UUID/g" /srv/xray/config.json
fi

if [ ! -d /srv/caddy/html ]; then
    mkdir -p /srv/caddy/html
    cp /defaults/index.html /srv/caddy/html/index.html
fi

chown -R srv:srv /defaults
chown -R srv:srv /srv
