#!/usr/bin/with-contenv sh

mkdir -p \
    /srv/caddy \
    /srv/caddy/log \
    /srv/xray \
    /srv/xray/certs \
    /srv/xray/log

touch /var/log/xray/access.log
touch /var/log/xray/error.log

CERTPATH="/srv/caddy/certificates/acme-v02.api.letsencrypt.org-directory"
UUID=${UUID:-"6744d9b8-5638-11eb-ae93-0242ac130002"}

if [ ! -f /srv/caddy/Caddyfile ]; then
    cp /defaults/Caddyfile /srv/caddy/Caddyfile
    if [[ -z "${DOMAIN}" || -z "${CFKEY}" ]]; then
        sed -i -e "/^https:\/\/__DOMAIN__:8443/,$ d" /srv/caddy/Caddyfile
        false | cp -i /defaults/example.key /srv/xray/certs/private.key 2>/dev/null
        false | cp -i /defaults/example.crt /srv/xray/certs/fullchain.crt 2>/dev/null
    else
        sed -i -e "s/__DOMAIN__/${DOMAIN}/g" /srv/caddy/Caddyfile
        sed -i -e "s/__CFKEY__/${CFKEY}/g" /srv/caddy/Caddyfile
        ln -sf $CERTPATH/${DOMAIN}/${DOMAIN}.crt /srv/xray/certs/fullchain.crt
        ln -sf $CERTPATH/${DOMAIN}/${DOMAIN}.key /srv/xray/certs/private.key
    fi
fi

if [ ! -f /srv/xray/config.json ]; then
    cp /defaults/xray.json /srv/xray/config.json
    sed -i -e "s/__UUID__/$UUID/g" /srv/xray/config.json
fi

if [ ! -d /srv/caddy/html ]; then
    mkdir -p /srv/caddy/html
    cp /defaults/index.html /srv/caddy/html/index.html
fi

chown -R srv:srv /defaults
chown -R srv:srv /srv
chown -R srv:srv /var/log/xray
